### ISSUE TITLE
whの発音の取り扱い

### ISSUE THREAD

**Issue by yncat** [actlaboratory/englishToKanaConverter#4]
英語の読みに近い方向に寄せるということならば、

where
when
which
whether
what

の今の読み方は、whの発音を抜いた読み方に修正したほうがいいのではないでしょうか？

実用上、whの発音は消えていることと、これらの単語に対して人文字多く発音されることが、個人的には不必要に感じられるためです。

検討していただけると幸いです。

**Comment by kitabatake1013** [comment]
発音的にはご指摘の通りですが、`WH`の音が消えると、不都合なことがあります。
例えば、`why`を「ワイ」と変換してしまうと、`Y`との区別が難しくなります。

ということで、これは現状のまま、変更しないことにします。
